NOTION_TOKEN="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"
GROQ_API_KEY="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"
QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.Ry5CoAOFS_8wl_f-ayzDWGxBIDmnaWybeNeLeXFH8I4"
QDRANT_HOST="https://dbc8e6e9-8d06-4c7d-9757-e82e00342e8e.us-east4-0.gcp.cloud.qdrant.io:6333"